name: weather_app
description: "weather in 2 units."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  home_widget: ^0.4.0-alpha.0
  weather: ^3.1.1
  material3_layout: ^0.0.7
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

 